import pandas as pd

expo = pd.read_csv('expo.csv')
expo.columns = ['Titular', 'Domicilio', 'Localidad', 'AgenteDestino', 'M3Esti',
       'Estado', 'Codigo_Coord', 'Coordinador', 'Codigo_Vend', 'Vendedor',
       'Origen', 'Destino', 'Fecha Apertura', 'Fecha Embalaje',
       'Fecha Fiscal', 'Fecha Salida', 'Fecha Llegada',
       'M3Reales', 'Libras', 'Kilos', 'Bultos']

expo.to_csv('expo.csv', index=False)


    data = [
        {
            "Titular": "Sanchez Laura",
            "Domicilio": "Av. Rivadavia 1000",
            "Localidad": "Salta",
            "AgenteDestino": "MoveNac Norte",
            "M3Esti": 10.0,
            "Estado": "Abierto",
            "Codigo_Coord": 21,
            "Coordinador": "Marcos Ruiz",
            "Codigo_Vend": 31,
            "Vendedor": "Silvia Gomez",
            "Origen": "Salta",
            "Destino": "Buenos Aires",
            "Fecha Apertura": "2025-03-01",
            "Fecha Embalaje": "",
            "Fecha Fiscal": "",
            "Fecha Salida": "",
            "Fecha Llegada": "",
            "M3Reales": "",
            "Libras": "",
            "Kilos": "",
            "Bultos": ""
        },
        {
            "Titular": "Martinez Pablo",
            "Domicilio": "Calle Mitre 200",
            "Localidad": "Santa Fe",
            "AgenteDestino": "MoveNac Sur",
            "M3Esti": 7.5,
            "Estado": "Embalado",
            "Codigo_Coord": 22,
            "Coordinador": "Marcos Ruiz",
            "Codigo_Vend": 32,
            "Vendedor": "Silvia Gomez",
            "Origen": "Santa Fe",
            "Destino": "Cordoba",
            "Fecha Apertura": "2025-02-20",
            "Fecha Embalaje": "2025-02-25",
            "Fecha Fiscal": "",
            "Fecha Salida": "",
            "Fecha Llegada": "",
            "M3Reales": 7.2,
            "Libras": 1587.0,
            "Kilos": 720.0,
            "Bultos": 10.0
        },
        {
            "Titular": "Fernandez Lucia",
            "Domicilio": "Av. San Juan 300",
            "Localidad": "Tucuman",
            "AgenteDestino": "MoveNac Centro",
            "M3Esti": 12.0,
            "Estado": "En deposito",
            "Codigo_Coord": 23,
            "Coordinador": "Marcos Ruiz",
            "Codigo_Vend": 33,
            "Vendedor": "Silvia Gomez",
            "Origen": "Tucuman",
            "Destino": "Mendoza",
            "Fecha Apertura": "2025-02-10",
            "Fecha Embalaje": "2025-02-15",
            "Fecha Fiscal": "2025-02-20",
            "Fecha Salida": "",
            "Fecha Llegada": "",
            "M3Reales": 11.8,
            "Libras": 2600.0,
            "Kilos": 1180.0,
            "Bultos": 14.0
        },
        {
            "Titular": "Perez Diego",
            "Domicilio": "Calle Sarmiento 400",
            "Localidad": "Neuquen",
            "AgenteDestino": "MoveNac Patagonia",
            "M3Esti": 9.0,
            "Estado": "Finalizado",
            "Codigo_Coord": 24,
            "Coordinador": "Marcos Ruiz",
            "Codigo_Vend": 34,
            "Vendedor": "Silvia Gomez",
            "Origen": "Neuquen",
            "Destino": "Chubut",
            "Fecha Apertura": "2025-01-15",
            "Fecha Embalaje": "2025-01-20",
            "Fecha Fiscal": "2025-01-25",
            "Fecha Salida": "2025-01-28",
            "Fecha Llegada": "2025-02-05",
            "M3Reales": 8.7,
            "Libras": 1918.0,
            "Kilos": 870.0,
            "Bultos": 12.0
        }
    ]